-- Load core configuration
require('core.options')
require('core.keymaps')
require('core.autocmds')
require('core.theme_picker')
require('core.lsp')
require('core.formatter')
require('core.statusline')
require('core.todo')
require('core.diagnostics')
