return {
	-- LSP Kinds
	Namespace = "󰅱",
	Text = "󰉿",
	Method = "󰆧",
	Function = "󰊕",
	Constructor = "",
	Field = "󰜢",
	Variable = "󰀫",
	Class = "󰠱",
	Interface = "",
	Module = "",
	Property = "󰜢",
	Unit = "󰑭",
	Value = "󰎠",
	Enum = "",
	Keyword = "󰌋",
	Snippet = "",
	Color = "󱓻",
	File = "󰈚",
	Reference = "󰈇",
	Folder = "󰉋",
	EnumMember = "",
	Constant = "󰏿",
	Struct = "󰙅",
	Event = "",
	Operator = "󰆕",
	TypeParameter = "󰊄",
	Table = "",
	Object = "󰅩",
	Tag = "",
	Array = "󰅪",
	Boolean = "󰨙",
	Number = "󰎠",
	Null = "󰟢",
	String = "󰉿",
	Calendar = "",
	Watch = "󰥔",
	Package = "",

	-- Diagnostics
	Error = " ",
	Warn = " ",
	Info = " ",
	Hint = "󰌵 ",

	-- Git
	Added = " ",
	Modified = " ",
	Removed = " ",
	Branch = " ",

	-- UI
	Folder = "󰉋 ",
	FolderOpen = "󰝰 ",
	FolderEmpty = "󰜌 ",
	File = "󰈚 ",
	FileReadOnly = "󰌾 ",

	-- Miscellaneous
	Supermaven = "",
	Copilot = "",
	Codeium = "",
	TabNine = "",
	BladeNav = "",
}
